export const rouletteData = [
  { name: '0', number: 0, color: 'green' },
  { name: '32', number: 0, color: 'red' },
  { name: '15', number: 0, color: 'black' },
  { name: '19', number: 0, color: 'red' },
  { name: '4', number: 0, color: 'black' },
  { name: '21', number: 0, color: 'red' },
  { name: '2', number: 0, color: 'black' },
  { name: '25', number: 0, color: 'red' },
  { name: '17', number: 0, color: 'black' },
  { name: '34', number: 0, color: 'red' },
  { name: '6', number: 0, color: 'black' },
  { name: '27', number: 0, color: 'red' },
  { name: '13', number: 0, color: 'black' },
  { name: '36', number: 0, color: 'red' },
  { name: '11', number: 0, color: 'black' },
  { name: '30', number: 0, color: 'red' },
  { name: '8', number: 0, color: 'black' },
  { name: '23', number: 0, color: 'red' },
  { name: '10', number: 0, color: 'black' },
  { name: '5', number: 0, color: 'red' },
  { name: '24', number: 0, color: 'black' },
  { name: '16', number: 0, color: 'red' },
  { name: '33', number: 0, color: 'black' },
  { name: '1', number: 0, color: 'red' },
  { name: '20', number: 0, color: 'black' },
  { name: '14', number: 0, color: 'red' },
  { name: '31', number: 0, color: 'black' },
  { name: '9', number: 0, color: 'red' },
  { name: '22', number: 0, color: 'black' },
  { name: '18', number: 0, color: 'red' },
  { name: '29', number: 0, color: 'black' },
  { name: '7', number: 0, color: 'red' },
  { name: '28', number: 0, color: 'black' },
  { name: '12', number: 0, color: 'red' },
  { name: '35', number: 0, color: 'black' },
  { name: '3', number: 0, color: 'red' },
  { name: '26', number: 0, color: 'black' },
]

export const rouletteDataForSelectOption = [
  { name: '0', number: 0, color: 'green' },
  { name: '1', number: 0, color: 'red' },
  { name: '2', number: 0, color: 'black' },
  { name: '3', number: 0, color: 'red' },
  { name: '4', number: 0, color: 'black' },
  { name: '5', number: 0, color: 'red' },
  { name: '6', number: 0, color: 'black' },
  { name: '7', number: 0, color: 'red' },
  { name: '8', number: 0, color: 'black' },
  { name: '9', number: 0, color: 'red' },
  { name: '10', number: 0, color: 'black' },
  { name: '11', number: 0, color: 'black' },
  { name: '12', number: 0, color: 'red' },
  { name: '13', number: 0, color: 'black' },
  { name: '14', number: 0, color: 'red' },
  { name: '15', number: 0, color: 'black' },
  { name: '16', number: 0, color: 'red' },
  { name: '17', number: 0, color: 'black' },
  { name: '18', number: 0, color: 'red' },
  { name: '19', number: 0, color: 'red' },
  { name: '20', number: 0, color: 'black' },
  { name: '21', number: 0, color: 'red' },
  { name: '22', number: 0, color: 'black' },
  { name: '23', number: 0, color: 'red' },
  { name: '24', number: 0, color: 'black' },
  { name: '25', number: 0, color: 'red' },
  { name: '26', number: 0, color: 'black' },
  { name: '27', number: 0, color: 'red' },
  { name: '28', number: 0, color: 'black' },
  { name: '29', number: 0, color: 'black' },
  { name: '30', number: 0, color: 'red' },
  { name: '31', number: 0, color: 'black' },
  { name: '32', number: 0, color: 'red' },
  { name: '33', number: 0, color: 'black' },
  { name: '34', number: 0, color: 'red' },
  { name: '35', number: 0, color: 'black' },
  { name: '36', number: 0, color: 'red' },
]

export const Zone1RouletteData = [
  { name: '0', number: 0, color: 'green' },
  { name: '32', number: 0, color: 'red' },
  { name: '15', number: 0, color: 'black' },
  { name: '19', number: 0, color: 'red' },
  { name: '4', number: 0, color: 'black' },
  { name: '21', number: 0, color: 'red' },
  { name: '2', number: 0, color: 'black' },
  { name: '25', number: 0, color: 'red' },
  { name: '17', number: 0, color: 'black' },
  { name: '34', number: 0, color: 'red' },
  { name: '6', number: 0, color: 'black' },
  { name: '27', number: 0, color: 'red' },
  { name: '13', number: 0, color: 'black' },
]

export const Zone2RouletteData = [
  { name: '36', number: 0, color: 'red' },
  { name: '11', number: 0, color: 'black' },
  { name: '30', number: 0, color: 'red' },
  { name: '8', number: 0, color: 'black' },
  { name: '23', number: 0, color: 'red' },
  { name: '10', number: 0, color: 'black' },
  { name: '5', number: 0, color: 'red' },
  { name: '24', number: 0, color: 'black' },
  { name: '16', number: 0, color: 'red' },
  { name: '33', number: 0, color: 'black' },
  { name: '1', number: 0, color: 'red' },
  { name: '20', number: 0, color: 'black' },
]

export const Zone3RouletteData = [
  { name: '14', number: 0, color: 'red' },
  { name: '31', number: 0, color: 'black' },
  { name: '9', number: 0, color: 'red' },
  { name: '22', number: 0, color: 'black' },
  { name: '18', number: 0, color: 'red' },
  { name: '29', number: 0, color: 'black' },
  { name: '7', number: 0, color: 'red' },
  { name: '28', number: 0, color: 'black' },
  { name: '12', number: 0, color: 'red' },
  { name: '35', number: 0, color: 'black' },
  { name: '3', number: 0, color: 'red' },
  { name: '26', number: 0, color: 'black' },
]

export let rouletteDataForChi = [
  {
    name: '0',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '32',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '15',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '19',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '4',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '21',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '2',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '25',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '17',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '34',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '6',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '27',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '13',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '36',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '11',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '30',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '8',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '23',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '10',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '5',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '24',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '16',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '33',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '1',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '20',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '14',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '31',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '9',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '22',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '18',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '29',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '7',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '28',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '12',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '35',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '3',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
  {
    name: '26',
    observed: 0,
    expected: 0,
    xSquare: 0,
    chi: 0,
    observedPocketBias: 0,
    standardDaviationFromExpected: 0,
  },
]
